services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gamecom-postgres
    environment:
      POSTGRES_DB: gamecom
      POSTGRES_USER: gamecom
      POSTGRES_PASSWORD: gamecom_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - gamecom-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gamecom-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://gamecom:gamecom_password@postgres:5432/gamecom
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      FRONTEND_URL: https://com.midaweb.be
      STEAM_API_KEY: ${STEAM_API_KEY:-}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - gamecom-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gamecom-frontend
    environment:
      VITE_API_URL: https://com.midaweb.be/api
      VITE_WS_URL: wss://com.midaweb.be
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - gamecom-network
    restart: unless-stopped

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: gamecom-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - gamecom-network
    restart: unless-stopped

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: gamecom-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email info@midaweb.be --agree-tos --no-eff-email -d com.midaweb.be
    depends_on:
      - nginx
    networks:
      - gamecom-network

volumes:
  postgres_data:

networks:
  gamecom-network:
    driver: bridge 